language: php

matrix:
  include:
    - php: 5.3
    - php: 5.3.3
      env: DEPENDENCIES='low'
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: DEPENDENCIES='dev'
    - php: 5.6
    - php: hhvm
    - php: 7.0
  allow_failures:
    - php: 7.0
    - env: DEPENDENCIES='dev'
  fast_finish: true

before_install:
  - composer selfupdate

script:
   - bin/phpspec run --format=pretty